"""Business Rules Engine for the Inventory Intelligence Engine.

Executes deterministic business rules BEFORE calling the LLM.
This reduces unnecessary LLM calls and provides fast, reliable
inventory assessments based on predefined thresholds.

Rules:
- Stock < Reorder Point -> High Priority
- Stock < Safety Stock -> Critical
- Lead Time > 14 days -> Supplier Risk
- Inventory Turnover < 2 -> Slow Moving
- Days of Supply > 90 -> Overstocked
- Days of Supply < 5 -> Stockout Risk
"""

from __future__ import annotations

import logging
from enum import Enum
from dataclasses import dataclass, field
from typing import Any

LOGGER = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class InventoryAlert:
    """An alert generated by a business rule."""
    rule_name: str
    severity: AlertSeverity
    message: str
    product_id: str
    current_value: float
    threshold: float


@dataclass
class BusinessRuleResult:
    """Result of evaluating business rules for a product."""
    product_id: str
    product_name: str
    alerts: list[InventoryAlert] = field(default_factory=list)
    overall_status: str = "Healthy"
    overall_confidence: float = 1.0

    @property
    def has_critical(self) -> bool:
        return any(a.severity == AlertSeverity.CRITICAL for a in self.alerts)

    @property
    def has_high(self) -> bool:
        return any(a.severity in (AlertSeverity.HIGH, AlertSeverity.CRITICAL) for a in self.alerts)

    @property
    def highest_severity(self) -> AlertSeverity:
        if self.has_critical:
            return AlertSeverity.CRITICAL
        if self.has_high:
            return AlertSeverity.HIGH
        if any(a.severity == AlertSeverity.WARNING for a in self.alerts):
            return AlertSeverity.WARNING
        return AlertSeverity.INFO

    def to_dict(self) -> dict[str, Any]:
        return {
            "product_id": self.product_id,
            "product_name": self.product_name,
            "overall_status": self.overall_status,
            "overall_confidence": self.overall_confidence,
            "highest_severity": self.highest_severity.value,
            "alerts": [
                {
                    "rule_name": a.rule_name,
                    "severity": a.severity.value,
                    "message": a.message,
                    "current_value": a.current_value,
                    "threshold": a.threshold,
                }
                for a in self.alerts
            ],
        }

    def to_prompt_context(self) -> str:
        """Build a concise business rules context for the LLM prompt."""
        lines = [
            f"Inventory Business Rules Analysis for {self.product_name} ({self.product_id}):",
            f"Overall Status: {self.overall_status}",
            f"Highest Severity: {self.highest_severity.value}",
        ]
        if self.alerts:
            lines.append("Active Alerts:")
            for a in self.alerts:
                lines.append(f"  [{a.severity.value.upper()}] {a.rule_name}: {a.message}")
        else:
            lines.append("No active alerts — all inventory health checks passed.")
        return "\n".join(lines)


def evaluate_business_rules(
    product_id: str,
    current_stock: int,
    safety_stock: int,
    reorder_point: int,
    lead_time_days: int,
    inventory_turnover: float,
    days_of_supply: float,
    forecast_demand: float,
    product_name: str = "",
) -> BusinessRuleResult:
    """Evaluate all business rules for a single product."""
    alerts: list[InventoryAlert] = []

    if safety_stock > 0 and current_stock <= safety_stock:
        alerts.append(InventoryAlert(
            rule_name="Stock Below Safety Stock", severity=AlertSeverity.CRITICAL,
            message=f"Stock ({current_stock}) below safety stock ({safety_stock}). Immediate replenishment required.",
            product_id=product_id, current_value=float(current_stock), threshold=float(safety_stock),
        ))

    if reorder_point > 0 and current_stock <= reorder_point:
        if not any(a.rule_name == "Stock Below Safety Stock" for a in alerts):
            alerts.append(InventoryAlert(
                rule_name="Stock Below Reorder Point", severity=AlertSeverity.HIGH,
                message=f"Stock ({current_stock}) below reorder point ({reorder_point}). Reorder needed.",
                product_id=product_id, current_value=float(current_stock), threshold=float(reorder_point),
            ))

    if lead_time_days > 14:
        alerts.append(InventoryAlert(
            rule_name="Supplier Lead Time Risk", severity=AlertSeverity.HIGH,
            message=f"Lead time ({lead_time_days}d) exceeds 14-day threshold.",
            product_id=product_id, current_value=float(lead_time_days), threshold=14.0,
        ))

    if lead_time_days > 21:
        alerts.append(InventoryAlert(
            rule_name="Critical Supplier Lead Time", severity=AlertSeverity.CRITICAL,
            message=f"Lead time ({lead_time_days}d) critically high (>21d). High stockout risk.",
            product_id=product_id, current_value=float(lead_time_days), threshold=21.0,
        ))

    if 0 < inventory_turnover < 2.0:
        alerts.append(InventoryAlert(
            rule_name="Slow Moving Inventory", severity=AlertSeverity.WARNING,
            message=f"Turnover ({inventory_turnover:.2f}x/yr) below 2x target.",
            product_id=product_id, current_value=inventory_turnover, threshold=2.0,
        ))

    if days_of_supply > 90:
        alerts.append(InventoryAlert(
            rule_name="Overstocked Inventory", severity=AlertSeverity.WARNING,
            message=f"Days of supply ({days_of_supply:.0f}) exceeds 90-day threshold.",
            product_id=product_id, current_value=days_of_supply, threshold=90.0,
        ))

    if 0 < days_of_supply < 5:
        alerts.append(InventoryAlert(
            rule_name="Stockout Risk", severity=AlertSeverity.CRITICAL,
            message=f"Only {days_of_supply:.0f} days of supply (<5). Stockout imminent.",
            product_id=product_id, current_value=days_of_supply, threshold=5.0,
        ))

    if current_stock <= 0:
        alerts.append(InventoryAlert(
            rule_name="Complete Stockout", severity=AlertSeverity.CRITICAL,
            message=f"Stock at {current_stock}. Complete stockout. Emergency replenishment required.",
            product_id=product_id, current_value=float(current_stock), threshold=1.0,
        ))

    if any(a.severity == AlertSeverity.CRITICAL for a in alerts):
        overall_status, overall_confidence = "Critical", 0.95
    elif any(a.severity == AlertSeverity.HIGH for a in alerts):
        overall_status, overall_confidence = "High Priority", 0.85
    elif any(a.severity == AlertSeverity.WARNING for a in alerts):
        overall_status, overall_confidence = "Warning", 0.75
    else:
        overall_status, overall_confidence = "Healthy", 0.95

    return BusinessRuleResult(
        product_id=product_id, product_name=product_name or product_id,
        alerts=alerts, overall_status=overall_status, overall_confidence=overall_confidence,
    )

